# Site settings
title: "suriya's stuffs"
description: "Exploring RL algorithms with intuitive explanations and practical implementations"
author: "Suriya Prakash"
email: your-email@example.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://SURIAPRAKASH1.github.io" # the base hostname & protocol for your site
github_url: "https://github.com/yourusername/your-rl-blog"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax

# Permalinks
permalink: /posts/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /posts/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
